# Generated by Django 4.2 on 2024-11-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_a',
            fields=[
                ('a_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='管理者No')),
                ('a_first', models.CharField(max_length=50, verbose_name='苗字')),
                ('a_name', models.CharField(max_length=50, verbose_name='名前')),
                ('a_pass', models.CharField(max_length=50, verbose_name='管理者パスワード')),
            ],
            options={
                'db_table': 'account_a',
            },
        ),
        migrations.CreateModel(
            name='Account_e',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False, verbose_name='従業員id')),
                ('e_first1', models.CharField(max_length=50, verbose_name='苗字')),
                ('e_last1', models.CharField(max_length=50, verbose_name='名前')),
                ('e_first2', models.CharField(max_length=50, verbose_name='苗字フリガナ')),
                ('e_last2', models.CharField(max_length=50, verbose_name='名前フリガナ')),
                ('hour', models.IntegerField(verbose_name='時給')),
            ],
            options={
                'db_table': 'account_e',
            },
        ),
    ]
