# Generated by Django 4.2 on 2024-12-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_a_name_account_a_a_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_a',
            name='a_first',
            field=models.CharField(max_length=50, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='account_a',
            name='a_last',
            field=models.CharField(max_length=50, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='account_a',
            name='a_no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='No'),
        ),
    ]
