# Generated by Django 4.2 on 2024-12-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_a_a_first_alter_account_a_a_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_a',
            name='a_no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='No.'),
        ),
    ]
