# Generated by Django 4.2 on 2024-12-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_a_a_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_a',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account_a',
            name='a_pass',
            field=models.CharField(max_length=128, verbose_name='管理者パスワード'),
        ),
    ]
