# Generated by Django 4.2 on 2024-12-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_a_is_active_alter_account_a_a_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_a',
            name='is_active',
        ),
    ]
