# Generated by Django 4.2 on 2024-12-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_a_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_a',
            name='a_pass',
            field=models.CharField(max_length=50, verbose_name='管理者パスワード'),
        ),
    ]
