# Generated by Django 4.2 on 2024-12-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_a_is_active_account_a_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_a',
            name='is_staff',
        ),
    ]
