# Generated by Django 4.2 on 2024-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_a_is_staff_account_a_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_e',
            name='e_first1',
            field=models.CharField(max_length=50, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='account_e',
            name='e_first2',
            field=models.CharField(max_length=50, verbose_name='セイ'),
        ),
        migrations.AlterField(
            model_name='account_e',
            name='e_last1',
            field=models.CharField(max_length=50, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='account_e',
            name='e_last2',
            field=models.CharField(max_length=50, verbose_name='メイ'),
        ),
    ]
