# Generated by Django 4.2 on 2024-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='勤怠id')),
                ('w_start', models.DateTimeField(verbose_name='勤怠開始時間')),
                ('w_end', models.DateTimeField(blank=True, null=True, verbose_name='休憩終了時間')),
                ('b_start', models.DateTimeField(blank=True, null=True, verbose_name='休憩開始')),
                ('b_end', models.DateTimeField(blank=True, null=True, verbose_name='休憩終了')),
                ('p_hour', models.IntegerField(blank=True, null=True, verbose_name='過去の時給')),
            ],
            options={
                'db_table': 'work',
            },
        ),
    ]
