# Generated by Django 4.2 on 2024-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='w_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='勤怠終了時間'),
        ),
    ]
