# Generated by Django 4.2 on 2024-11-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswork', '0002_alter_work_w_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='有給id')),
                ('p_time', models.DateField(verbose_name='有給日付')),
            ],
            options={
                'db_table': 'paid',
            },
        ),
    ]
