# Generated by Django 4.2 on 2024-11-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('letswork', '0003_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='a_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account_a', verbose_name='管理者id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='e_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.account_e', verbose_name='従業員id'),
            preserve_default=False,
        ),
    ]
