# Generated by Django 4.2 on 2024-12-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letswork', '0004_paid_a_id_work_e_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid',
            old_name='a_id',
            new_name='a_no',
        ),
    ]
