# Generated by Django 4.2 on 2025-01-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_e_e_first1_alter_account_e_e_first2_and_more'),
        ('letswork', '0006_work_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='e_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account_e', verbose_name='従業員id'),
        ),
    ]
