# Generated by Django 4.2 on 2025-01-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letswork', '0007_paid_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_duration_formatted',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='労働時間（HH:MM形式）'),
        ),
    ]
