# Generated by Django 4.2 on 2025-01-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letswork', '0008_work_work_duration_formatted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_duration_formatted',
        ),
    ]
