# Generated by Django 4.2 on 2025-01-31 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_e_e_first1_alter_account_e_e_first2_and_more'),
        ('letswork', '0010_work_work_duration_formatted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_salary', models.FloatField(default=0)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account_e')),
            ],
        ),
    ]
